blog/urls.py
from django.conf.urls import url
from . import views
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [

    url(r'^$', RedirectView.as_view(url='/1', permanent=False)),
    url(r'^(?P<page>\d+)/$', views.index, name="index"),
    url(r'^blogs/(?P<page>\d+)/$', views.blogs, name="blogs"),
    url(r'^philosophy/', views.philosophy, name="philosophy"),
    url(r'^contact/$', views.contact, name="contact"),
]

trj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("blog.urls", namespace="blog")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField

now = timezone.now()
YESNO_CHOICES = (
    (True, "Yes"),
    (False, "No"),
)

class Photo(models.Model):
    date_added = models.DateField(default=now)
    title = models.CharField(max_length=150)
    caption = models.TextField(blank=True, null=True)
    image = models.FileField(max_length=150, upload_to="images")
    published = models.BooleanField(default=True, choices=YESNO_CHOICES)
    featured = models.BooleanField(default=False, choices=YESNO_CHOICES)

    def __str__(self):
        return self.title



class Blog(models.Model):
    date_added = models.DateTimeField(default=timezone.now)
    published = models.BooleanField(choices=YESNO_CHOICES, default=True)
    featured = models.BooleanField(choices=YESNO_CHOICES, default=True)
    title = models.CharField(max_length=150)
    author_name = models.CharField(max_length=150)
    intro_text = models.TextField(blank=True, null=True)
    image = models.FileField(upload_to="blogs/intro-images", blank=True, null=True, max_length=200)
    content = RichTextUploadingField(blank=True, null=True)
    tags = models.CharField(max_length=250)

    def __str__(self):
        return self.title

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Photo, Blog
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger




def index(request, page):
    page=int(page)
    photos_list=Photo.objects.all()
    paginator = Paginator(photos_list, 6)

    try:
        photos = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        photos = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        photos = paginator.page(paginator.num_pages)


    return render(request, "index.html", {
        'photos':photos
    })

def blogs(request, page):
    page=int(page)
    blogs_list=Blog.objects.all()
    paginator = Paginator(blogs_list, 6)

    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        blogs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        blogs = paginator.page(paginator.num_pages)


    return render(request, "blogs/blog.html", {
        'blogs':blogs
    })

def philosophy(request):
    return render(request, "philosophy.html", {})

def contact(request):
    return render(request, "contact.html", {})

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<link rel="shortcut icon" href="{% static "style/images/favicon.png" %}">
<title>{% block title %}{% endblock title %} | The Royal Journal</title>
<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/plugins.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "style.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/color/blue.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "type/icons.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "custom.css" %}">
<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700%7CKarla:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
<div class="content-wrapper">

  {% include "header.html" %}

  {% block content %}
  {% endblock content %}

  {% include "footer.html" %}

</div>
</body>
<script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/plugins.js" %}"></script>
<script type="text/javascript" src="{% static "js/scripts.js" %}"></script>
</html>

templates/blogs/blog.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Home
{% endblock title %}

{% block content %}


<div class="content-wrapper">

  <div class="dark-wrapper">
    <div class="container inner">
      <div class="blog row">
        <div class="col-sm-8 blog-content grid-view">
          <div class="blog-content">
            <div class="row blog-posts">
              {% for each in blogs %}

              <div class="post col-sm-12 col-md-6">
                <figure class="overlay">
                  <a href="#">
                    <img src="{{each.image.url}}" alt="blog image" />
                  </a>
                </figure>
                <div class="post-content">
                  <h3 class="post-title"><a href="blog-post.html">{{each.title}}</a></h3>
                  <div class="meta">
                    <span class="date">{{each.date_added}}</span>
                  </div>
                  <p>{{each.intro_text}}</p>
                  <a href="blog-post.html" class="more">Read More</a> </div>

                </div>
                <hr />
                {%endfor%}

              </div>

            </div>

            <div class="pagination">
              <ul>
                {% if blogs.has_previous %}
                  <li><a class="btn btn-square btn-icon" href="{% url "blog:blogs" blogs.previous_page_number %}"><i class="ion-android-arrow-back"></i></a></li>

                {% else %}
                <li></li>

                {% endif %}


                <li class="active"><a class="btn btn-square" href="#"><span>  Page {{ blogs.number }} of {{ blogs.paginator.num_pages }} </span></a></li>

                <!-- <li><a class="btn btn-square" href="#"><span>2</span></a></li>
                <li><a class="btn btn-square" href="#"><span>3</span></a></li> -->

                {% if blogs.has_next %}
                  <li><a class="btn btn-square btn-icon" href="{% url "blog:blogs" blogs.next_page_number %}"><i class="ion-android-arrow-forward"></i></a></li>

                {% else %}
                <li></li>

                {% endif %}


              </ul>
            </div>
            <!-- /.pagination -->





          </div>
          <!-- /.blog-content -->

          <aside class="col-sm-4 sidebar">
            <div class="sidebox widget">
              <h3 class="widget-title">About Us</h3>
              <figure> <img src="style/images/art/about2.jpg" class="img-auto" alt="" /> </figure>
              <div class="divide10"></div>
              <p>Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum.</p>
              <ul class="social">
                <li> <a href="#"><i class="ion-social-rss"></i></a> </li>
                <li> <a href="#"><i class="ion-social-facebook"></i></a> </li>
                <li> <a href="#"><i class="ion-social-twitter"></i></a> </li>
                <li> <a href="#"><i class="ion-social-instagram"></i></a> </li>
                <li> <a href="#"><i class="ion-social-vimeo"></i></a> </li>
                <li> <a href="#"><i class="ion-social-whatsapp"></i></a> </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <!-- /.widget -->

            <div class="sidebox widget">
              <h3 class="widget-title">Popular Posts</h3>
              <ul class="post-list">
                <li>
                  <figure class="overlay small"> <a href="blog-post.html"><img src="style/images/art/a1.jpg" alt="" /> </a> </figure>
                  <div class="post-content">
                    <h4 class="post-title"> <a href="blog-post.html">Magna Mollis Ultricies Mauris</a> </h4>
                    <div class="meta"><span class="date">12 Nov 2014</span><span class="category"><a href="#">Urban</a></span></div>
                  </div>
                </li>
                <li>
                  <figure class="overlay small"> <a href="blog-post.html"><img src="style/images/art/a2.jpg" alt="" /> </a> </figure>
                  <div class="post-content">
                    <h4 class="post-title"> <a href="blog-post.html">Ornare Nullam Risus Cursus</a> </h4>
                    <div class="meta"><span class="date">12 Nov 2014</span><span class="category"><a href="#">Still Life</a></span></div>
                  </div>
                </li>
                <li>
                  <figure class="overlay small"> <a href="blog-post.html"><img src="style/images/art/a3.jpg" alt="" /> </a> </figure>
                  <div class="post-content">
                    <h4 class="post-title"> <a href="blog-post.html">Euismod Nullam Fusce Dapibus</a> </h4>
                    <div class="meta"><span class="date">12 Nov 2014</span><span class="category"><a href="#">Conceptual</a></span></div>
                  </div>
                </li>
              </ul>
              <!-- /.post-list -->
            </div>
            <!-- /.widget -->

            <div class="sidebox widget">
              <h3 class="widget-title">Categories</h3>
              <ul class="list circled">
                <li><a href="#">Lifestyle (21)</a></li>
                <li><a href="#">Photography (19)</a></li>
                <li><a href="#">Journal (16)</a></li>
                <li><a href="#">Works (7)</a></li>
                <li><a href="#">Conceptual (12)</a></li>
                <li><a href="#">Videography</a></li>
              </ul>
            </div>
            <!-- /.widget -->

            <div class="sidebox widget">
              <h3 class="widget-title">Tags</h3>
              <ul class="tag-list">
                <li><a href="#" class="btn btn-white">Still Life</a></li>
                <li><a href="#" class="btn btn-white">Urban</a></li>
                <li><a href="#" class="btn btn-white">Journal</a></li>
                <li><a href="#" class="btn btn-white">Nature</a></li>
                <li><a href="#" class="btn btn-white">Landscape</a></li>
                <li><a href="#" class="btn btn-white">Macro</a></li>
                <li><a href="#" class="btn btn-white">Workshop</a></li>
                <li><a href="#" class="btn btn-white">Photography</a></li>
              </ul>
            </div>
            <!-- /.widget -->
            <div class="sidebox widget">
              <h3 class="widget-title">Instagram</h3>
              <div class="tiles instagram">
                <div id="instafeed-widget" class="items row row-offset-0"></div>
              </div>
              <!--/.tiles -->
            </div>
            <!-- /.widget -->
            <div class="sidebox widget">
              <h4 class="widget-title">Search</h4>
              <form class="searchform" method="get">
                <input type="text" id="s1" name="s" value="Search something" onfocus="this.value=''" onblur="this.value='Search something'">
              </form>
            </div>
            <!-- /.widget -->
          </aside>
          <!-- /column .sidebar -->

        </div>
        <!-- /.blog -->
      </div>
      <!-- /.container -->
    </div>


  </div>

  {% endblock content %}

templates/contact.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Contact
{% endblock title %}

{% block content %}

  <div class="google-map h450" data-lat="51.211215" data-lng="3.226287"></div>
  <div class="light-wrapper">
    <div class="container inner">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="row">
            <div class="col-sm-4 text-center"> <span class="icon icon-m bm20"><i class="budicon-pin"></i></span>
              <p>Delhi Nerds<br>
                C2, Sector 1, Noida, UP - 201301</p>
            </div>
            <!--/column -->
            <div class="col-sm-4 text-center"> <span class="icon icon-m bm20"><i class="budicon-telephone"></i></span>
              <p>011-65000357<br>
            </div>
            <!--/column -->
            <div class="col-sm-4 text-center"> <span class="icon icon-m bm20"><i class="budicon-profile"></i></span>
              <p><a class="nocolor" href="mailto:contact@theroyaljournal.in">contact@theroyaljournal.in</a><br>
                <a class="nocolor" href="mailto:hello@delhinerds.com">hello@delhinerds.com</a></p>
            </div>
            <!--/column -->
          </div>
          <!--/.row -->

          <div class="divide70"></div>
          <h3 class="text-center">Get in Touch</h3>
          <p class="text-center">Nullam quis risus eget urna mollis ornare vel eu leo. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Integer posuere erat.</p>
          <div class="divide10"></div>
          <div class="form-container">
            <form action="" method="post" class="vanilla vanilla-form" novalidate="novalidate">
              <div class="row">
                <div class="col-sm-6 rp10">
                  <div class="form-field">
                    <label>
                      <input type="text" name="name" placeholder="Your name" required="required">
                    </label>
                  </div>
                  <!--/.form-field -->
                </div>
                <!--/column -->
                <div class="col-sm-6 lp10">
                  <div class="form-field">
                    <label>
                      <input type="email" name="email" placeholder="Your e-mail" required="required">
                    </label>
                  </div>
                  <!--/.form-field -->
                </div>
                <!--/column -->
                <div class="col-sm-6 rp10">
                  <div class="form-field">
                    <label>
                      <input type="tel" name="tel" placeholder="Phone">
                    </label>
                  </div>
                  <!--/.form-field -->
                </div>
                <!--/column -->
                <div class="col-sm-6 lp10">
                  <div class="form-field">
                    <label class="custom-select">
                      <select name="department" required="required">
                        <option value="">Select Department</option>
                        <option value="Sales">Sales</option>
                        <option value="Marketing">Marketing</option>
                        <option value="Support">Customer Support</option>
                        <option value="Other">Other</option>
                      </select>
                      <span><!-- fake select handler --></span> </label>
                  </div>
                  <!--/.form-field -->
                </div>
                <!--/column -->

                <div class="col-sm-12">
                  <textarea name="message" placeholder="Type your message here..." required="required"></textarea>
                  <div class="radio-set">
                    <label>Subject:</label>
                    <label>
                      <input type="radio" name="subject" value="General">
                      <span><!-- fake radio --></span> General</label>
                    <label>
                      <input type="radio" name="subject" value="Hi">
                      <span><!-- fake radio --></span> Say Hi</label>
                    <label>
                      <input type="radio" name="subject" value="Other">
                      <span><!-- fake radio --></span> Other</label>
                  </div>
                  <!--/.radio-set -->
                  <input type="submit" class="btn" value="Send" data-error="Fix errors" data-processing="Sending..." data-success="Thank you!">
                  <footer class="notification-box"></footer>
                </div>
                <!--/column -->

              </div>
              <!--/.row -->

            </form>
            <!--/.vanilla-form -->
          </div>
          <!--/.form-container -->

        </div>
        <!--/column -->

      </div>
      <!--/.row -->
    </div>
    <!-- /.container -->
  </div>
  <!-- /.light-wrapper -->

</div>

{% endblock content %}

templates/footer.html
<footer class="inverse-wrapper">
  <div class="sub-footer">
    <div class="container-fluid inner">
      <p class="pull-left">© 2017 The Royal Journal. All rights reserved. Designed by <a href="http://www.delhinerds.com" target="_blank">Delhi Nerds</a></p>
      <ul class="social pull-right">
        <li> <a href="#"><i class="ion-social-facebook"></i></a> </li>
        <li> <a href="#"><i class="ion-social-twitter"></i></a> </li>
        <li> <a href="#"><i class="ion-social-instagram"></i></a> </li>
        <li> <a href="#"><i class="ion-social-vimeo"></i></a> </li>
        <li> <a href="#"><i class="ion-social-whatsapp"></i></a> </li>
      </ul>
    </div>
  </div>
</footer>

templates/header.html
{% load staticfiles %}

<div class="navbar navbar-default default classic full" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand"><a href="{% url "blog:index" 1 %}"><img src="{% static "logo.png" %}" alt="The Royal Journal Logo" style="height:100px;" /></a></div>
      <div class="nav-bars-wrapper">
        <div class="nav-bars-inner">
          <div class="nav-bars" data-toggle="collapse" data-target=".navbar-collapse"><span></span></div>
        </div>
        <!-- /.nav-bars-inner -->
      </div>
      <!-- /.nav-bars-wrapper -->
    </div>
    <!-- /.nav-header -->

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="#!">Photos<span class="caret"></span></a>
        </li>
        <li><a href="{% url "blog:blogs" 1 %}">Blog<span class="caret"></span></a>
        </li>
        <li><a href="{% url "blog:philosophy" %}">Philosophy<span class="caret"></span></a>
        </li>
        <li><a href="{% url "blog:contact" %}">Contact<span class="caret"></span></a>
        </li>
      </ul>
    </div>
    <!--/.nav-collapse -->

  </div>
  <!--/.container-fluid -->
</div>
<!--/.navbar -->

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Home
{% endblock title %}

{% block content %}

<div class="light-wrapper">
  <div class="container-fluid inner2 tp0">
    <div class="collage-wrapper">
      <div id="collage-large" class="collage effect-parent light-gallery">
        {% for each in photos %}
        <div class="collage-image-wrapper">
          <div class="overlay">
            <a href="{{each.image.url}}" class="lgitem" data-sub-html="#{{each.caption}}">
              <img src="{{each.image.url}}" style="width:675px; height:450px;" alt="" />
            </a>
            <div id={{each.caption}} class="hidden">
              <h3>{{each.title}}</h3>
              <p>{{each.caption}}</p>
            </div>
          </div>
        </div>
        {% endfor %}


      </div>
    </div>
    <div class="col-md-5"></div>

    <div class="col-md-4">
      <nav aria-label="Page navigation" class="navigation">
        <ul class="pagination" >
          {% if photos.has_previous %}
          <li>
            <a href="{% url "blog:index" photos.previous_page_number %}" aria-label="Previous">
              <i class="fa fa-chevron-left" aria-hidden="true"></i>
              <span aria-hidden="true">Prev</span>
            </a>
          </li>
          {% else %}
          <li></li>

          {% endif %}

          <!-- <li><a href="#">1</a></li> -->
          <li class="active">
            <a href="#">
              <span aria-hidden="true">
                  Page {{ photos.number }} of {{ photos.paginator.num_pages }}
              </span>

            </a>
          </li>

          <!-- <li><a href="#">3</a></li>
          <li><a href="#">4</a></li>
          <li><a href="#">5</a></li> -->
          {% if photos.has_next %}
          <li>
            <a href="{% url "blog:index" photos.next_page_number %}" aria-label="Next">
              <span aria-hidden="true">Next</span>
              <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
          </li>
          {% else %}
          <li></li>

          {% endif %}
        </ul>
      </nav>
    </div>

    <div class="col-md-5"></div>

  </div>

  <!-- /.container-fluid -->
</div>

<!-- /.light-wrapper -->


{% endblock content %}

templates/philosophy.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Philosophy
{% endblock title %}

{% block content %}

  <div class="dark-wrapper">
    <div class="container inner">
      <div class="row">
        <div class="col-md-5 rp20 bm20">
          <figure><img src="{% static "images/art/about.jpg" %}" alt="" /></figure>
        </div>
        <!-- /column -->
        <div class="col-md-7">
          <h3>Who is Behind?</h3>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Maecenas sed diam eget risus varius blandit sit amet non magna. Aenean lacinia bibendum nulla sed consectetur. Vestibulum id ligula porta felis euismod semper. Nullam id dolor id nibh ultricies vehicula ut id elit, fusce dapibus, tellus ac cursus commodo. Cras mattis consectetur purus sit amet fermentum. Vestibulum id ligula.</p>
          <blockquote>
            <p> Pellentesque non diam et tortor dignissim bibendum. Neque sit amet mauris egestas quis mattis velit fringilla. Curabitur viver justo sed scelerisque. Cras mattis consectetur purus sit amet fermentum.</p>
          </blockquote>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Nullam id dolor id nibh ultricies vehicula ut id elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
          <h3>Elsewhere</h3>
          <ul class="social">
            <li> <a href="#"><i class="ion-social-facebook"></i></a> </li>
            <li> <a href="#"><i class="ion-social-twitter"></i></a> </li>
            <li> <a href="#"><i class="ion-social-instagram"></i></a> </li>
            <li> <a href="#"><i class="ion-social-vimeo"></i></a> </li>
            <li> <a href="#"><i class="ion-social-linkedin"></i></a> </li>
          </ul>
        </div>
        <!-- /column -->

      </div>
      <!-- /.row -->
    </div>
    <!-- /.container -->
  </div>
  <!-- /.dark-wrapper -->

{% endblock content %}